### ISSUE TITLE
Build error: ENOENT: no such file or directory, rename 

### ISSUE THREAD

**Issue by clementbiron** [OpenTermsArchive/opentermsarchive.org#197]
Error [occured](https://github.com/ambanum/OpenTermsArchive.org/actions/runs/3531735694/jobs/5925235460) from the build of this [PR](https://github.com/ambanum/OpenTermsArchive.org/pull/193).

I tried to update `next`, `react` and `react-dom` to the latest versions but this does not fix the bug.

```
 > Build error occurred
[Error: ENOENT: no such file or directory, rename '/home/runner/work/OpenTermsArchive.org/OpenTermsArchive.org/.next/export/en/media.html' -> '/home/runner/work/OpenTermsArchive.org/OpenTermsArchive.org/.next/server/pages/en/media.html'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path: '/home/runner/work/OpenTermsArchive.org/OpenTermsArchive.org/.next/export/en/media.html',
  dest: '/home/runner/work/OpenTermsArchive.org/OpenTermsArchive.org/.next/server/pages/en/media.html'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! OpenTermsArchive.org@1.29.0 build: `next build --debug`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the OpenTermsArchive.org@1.29.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-11-23T11_44_22_072Z-debug.log
Error: Process completed with exit code 1.
```

**Comment by MattiSG** [comment]
> I tried to update `next`, `react` and `react-dom` to the latest versions but this does not fix the bug.

If you have that implemented and tested somewhere, please open a PR, this is always useful 🙂

**Comment by clementbiron** [comment]
> > I tried to update `next`, `react` and `react-dom` to the latest versions but this does not fix the bug.
> 
> If you have that implemented and tested somewhere, please open a PR, this is always useful 🙂

Ok, I finaly fixed the build error by updating the dependencies, see #200

**Comment by MattiSG** [comment]
Unfortunately the build error still seems present in #193 even after #200 was merged 🙁

**Comment by clementbiron** [comment]
The error was circumvented in https://github.com/ambanum/OpenTermsArchive.org/pull/202 by moving the file to `parts` folder.  

This should be investigated.

**Comment by martinratinaud** [comment]
@clementbiron I can check if still needed but not sure how to test it

**Comment by clementbiron** [comment]
Use [this branch](https://github.com/ambanum/OpenTermsArchive.org/tree/try_fix_enoent) and run `npm run build`, you could also see the build error [here](https://github.com/ambanum/OpenTermsArchive.org/actions/runs/3997744880/jobs/6859472351). If that is not enought explicit we can synchronize.

**Comment by martinratinaud** [comment]
@clementbiron here is how it is supposed to work

Pages in `content/pages` are handled by `src/pages/[...paths].tsx`. All mdx files in this folder with result in pages after the build.
So, in this case, the `/media` page will be built as `content/pages/en/media.tsx` exists.

In addition to that, a `src/pages/media.tsx` exists, which also creates a `/media` page

Even though the error message is not giving any clue of what happens, the problem resides in this conflict.

You should thus never create a file with the same base name in both `src/pages` and `content/pages/<lang>`

Let me know if you need more explanations
