### ISSUE TITLE
Unsightly blur on the logos of the maintainers

### ISSUE THREAD

**Issue by clementbiron** [OpenTermsArchive/opentermsarchive.org#225]
A blur appear with Chromium `Version 98.0.4694.0 ` and Chrome `Version 111.0.5563.146 ` on the homepage collections list.

![image](https://user-images.githubusercontent.com/364319/228468357-4fceb606-358f-4bd1-b52f-f8b98e040a2c.png)

**Comment by MattiSG** [comment]
Can't reproduce with Chrome 105 nor Firefox 116 :wink:
