### ISSUE TITLE
Correct all dead links on the website

### ISSUE THREAD

**Issue by MattiSG** [OpenTermsArchive/opentermsarchive.org#229]
Lack of tests have made us twice ship broken links, and we don't know how many other are there. This should not happen anymore. Add automated tests in CI for broken links, and fix the ones that are detected.

**Comment by clementbiron** [comment]
I spent some time studying the different solutions. 

- ❌ [Link Checker,](https://www.npmjs.com/package/link-checker
) (_6 Collaborators, 773 Weekly Downloads,  last update Oct 8, 2021_). Do not meet the necessary maintenance conditions.
- ❌ [html-proofer.js ](https://www.npmjs.com/package/html-proofer.js
) (_1 collaborator, 18 Weekly Downloads, last update Aug 30, 2022_). Do not meet the necessary maintenance conditions.
- ❌ [HTMLProofer](https://github.com/gjtorikian/html-proofer) (_72 contributors, last update  Apr 18, 2023_) which is implemented in a GitHub action named [proof-html](https://github.com/marketplace/actions/proof-html) (_989 contributors, last update  Feb 21, 2023_). The .next folder generated by the `next build` command is not quite a static file export (it needs Node to work) and and running this library on it would require many exceptions and workaround. I tried to make a real static export with the command `next export` but it is currently not compatible with our code base. The following error is raised: `Error: i18n support is not compatible with next export.`
- ✅ [linkinator](https://github.com/JustinBeckwith/linkinator) (_23 contributors, last update Mar 25, 2023_), a JavaScript lib that allow to crawling websites and validating links. Suggested implementation made in [this pull request](https://github.com/OpenTermsArchive/opentermsarchive.org/pull/230).

**Comment by MattiSG** [comment]
Implemented in https://github.com/OpenTermsArchive/opentermsarchive.org/pull/230.
