### ISSUE TITLE
Newsletter Feature on Website returns 404

### ISSUE THREAD

**Issue by emmanuellar** [OpenTermsArchive/opentermsarchive.org#242]
### Problem Statement
I tried to sign up for the newsletter on the website, and after entering my email, it returned a 404 error. I assumed my subscription didn't go through, however, I saw an email from the newsletter platform asking me to confirm my subscription. Then on clicking on the confirm subscription button, it led me to a blank dark page, and a 404 appeared on the web tab.

### Additional Information
<img width="1512" alt="Screen Shot 2023-06-29 at 09 34 24" src="https://github.com/Cli4d/DPG-OS-CM-Open-Terms-Archive/assets/41474439/3a318133-d5ad-4257-8486-90b9c924cc42">

### What happens if this is not addressed
This varies across various outcomes
- If the team is currently sending out newsletters, this means that new subscribers aren't able to join the email list
- If the team is collating emails in order to send out notices to the community, it means that recent notices aren't getting to potential members as a result of the glitches with the newsletter platform

### Recommended Action Items
- [ ] Add a priority label to this issue (OTA team)
- [ ] Add a project label to this issue
- [ ] Discuss with a Community Manager at Open Terms Archive
- [ ] Discuss with the Open Terms Archive team to find out if this is something to prioritize or not

**Comment by MattiSG** [comment]
The subscription process is actually function, but the confirmation page at `https://opentermsarchive.org/en/subscribe/confirm` does yield a 404 since #216. It should be partially reverted.
