### ISSUE TITLE
Unclear use of the term "reuses" and "Exemples"

### ISSUE THREAD

**Issue by emmanuellar** [OpenTermsArchive/opentermsarchive.org#243]
### Problem Statement
Use of the term "reuses" and "exemples"

### Additional Information
There's a section of the homepage called "reuses",  there's also another section under the media page titled "Exemples"  
I quickly pulled up a google search just to make sure I still understand what reuse and exemple means, and their meaning from my search doesn't tally with that I believe those section wants to convey.

### What happens if this is not addressed
It's a tad unclear what reuse means here, as reuse means "to use something again" which is not consistent with the content of the session. This can be confusing to the website visitors, and potentials community members.

### Resources
<img width="1495" alt="Screen Shot 2023-07-09 at 13 54 24" src="https://github.com/Cli4d/DPG-OS-CM-Open-Terms-Archive/assets/41474439/8d161122-50f7-4889-875b-f52da8e62efa">

<img width="1497" alt="Screen Shot 2023-07-09 at 13 54 37" src="https://github.com/Cli4d/DPG-OS-CM-Open-Terms-Archive/assets/41474439/af7cf5b2-f5b9-4878-8a88-890a75e53a5b">

### Recommended Action Items
- [ ] Add a priority label to this issue (OTA team)
- [ ] Add a project label to this issue
- [ ] Discuss with a Community Manager at Open Terms Archive
- [ ] Discuss with the Open Terms Archive team
- [ ] Make a new issue in the project repository

### Proposed Solution
Replace reuses with Use Cases, and replace Exemples with For example, or Example
Replace Reuses with Built with Open Terms Archive

**Comment by emmanuellar** [comment]
> Is this fully implemented by #239 and #244? 🙂

Yes it is! @MattiSG

**Comment by MattiSG** [comment]
When an issue is implemented, please close it to enable keeping track of what is left to do 😊
