### ISSUE TITLE
There is no visible link or reference to the GitHub link in the website

### ISSUE THREAD

**Issue by Cli4d** [OpenTermsArchive/opentermsarchive.org#245]
### Problem Statement
We need to add a visible reference to the Open Terms Archive GitHub organization/repository on the website so that contributors can be easily directed to the GitHub org/repo if they want to look at it

### What happens if this is not addressed
If this issue is left unresolved, we may lose possible contributors who are interested in looking at the GitHub repo/org.

### Recommended Action Items
- [ ] Add a priority label to this issue (OTA team)
- [x] Add a project label to this issue
- [ ] Discuss with a Community Manager at Open Terms Archive
- [ ] Discuss with the Open Terms Archive team
- [ ] Make a new issue in the project repository

### Potential solutions [draft]
We need to add a link for the GitHub organization at the footer of the website

**Comment by clementbiron** [comment]
Would it be enough to add a link in the form of a logo in the header?
<img width="1256" alt="image" src="https://github.com/OpenTermsArchive/opentermsarchive.org/assets/364319/f12ca762-1385-416b-a1e6-fdc023cb867d">

**Comment by MattiSG** [comment]
> in the header?

I would prefer that we avoid adding more entries to our header 🙂 from my point of view, GitHub should be treated as other social media and contact points, in the footer like Mastodon and Email.

**Comment by Cli4d** [comment]
Yeah I agree with @MattiSG. I think a better way is to have the logo in the footer. I'm not so sure if having it alongside the label of _Source Code_ will be bad in terms of UI and consistency. If so I think we can leave it as it is for now

**Comment by clementbiron** [comment]
We've added a GitHub icon in the header that links to the Open Terms Archive organisation, so I'm closing this ticket. Thanks Clifford!
