### ISSUE TITLE
Reword the labels for the collections button on the website

### ISSUE THREAD

**Issue by Cli4d** [OpenTermsArchive/opentermsarchive.org#246]
### Problem Statement
We need to reword the label for the industries, languages, and jurisdictions button on the website and make it descriptive so that it doesn't mislead potential contributors on the website

### Additional Information
_A gif showing the button labels_
![msedge_NSb7ucVlCk](https://github.com/Cli4d/DPG-OS-CM-Open-Terms-Archive/assets/56266330/89043cce-14db-4b6a-b143-99c0a3af2cab)

### What happens if this is not addressed
Potential contributors visiting the website will click on the button expecting to see either the industry's history or probably a commit history for the project but instead, are taken to the github repository.

### Recommended Action Items
- [ ] Add a priority label to this issue (OTA team)
- [x] Add a project label to this issue
- [ ] Discuss with a Community Manager at Open Terms Archive
- [ ] Discuss with the Open Terms Archive team
- [ ] Make a new issue in the project repository

### Potential solutions [draft]
We could create an issue and reword the label for those buttons as *Check out the repository* or *GitHub Repository*

**Comment by MattiSG** [comment]
@Cli4d missing a specific alternative suggestion, I will close this issue. Feel free to reopen it if you still find the button wording problematic and have an idea how to improve it!
