### ISSUE TITLE
Use logo as social card preview

### ISSUE THREAD

**Issue by MattiSG** [OpenTermsArchive/opentermsarchive.org#278]
Currently, the social card preview is the first collection partner's logo.

![linkedin](https://github.com/OpenTermsArchive/opentermsarchive.org/assets/222463/c09c675d-c2bd-4226-9aa9-b31e7dc4f409)

**Comment by clementbiron** [comment]
I can't reproduce, on which platform that happen?

**Comment by MattiSG** [comment]
LinkedIn.
